apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# dev: 로컬 개발 / Minikube 환경
# kubectl apply -k k8s/overlays/dev

resources:
  - ../../

namePrefix: dev-

commonLabels:
  env: dev

patches:
  - path: patch-dev.yaml
    target:
      kind: Deployment
      name: psar-trading-bot
  - path: patch-prometheus-dev.yaml
    target:
      kind: StatefulSet
      name: prometheus
