apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# prod: 실제 운영 환경
# kubectl apply -k k8s/overlays/prod

resources:
  - ../../

namePrefix: prod-

commonLabels:
  env: prod

patches:
  - path: patch-prod.yaml
    target:
      kind: Deployment
      name: psar-trading-bot
  - path: patch-prometheus-prod.yaml
    target:
      kind: StatefulSet
      name: prometheus
